### ISSUE TITLE
Feature Request : Support for Ahead of Time Compilation and Server Side Rendering

### ISSUE THREAD

**Issue by RohitRane** [FountainJS/generator-fountain-angular2#101]
## Description

It would be very helpful if you support Ahead of Time compilation in your scaffolding as additional feature.
There are no good material for AoT integration with webpack application.

I have noticed that a lot of time is lost in rendering the first view with Just in Time compilation due to the template compilation.

This becomes a hindrance if you are developing 
1. an E-commerce or
2. Mobile Web Application with Angular 
3. Popping a view in a separate new tab.

Do you have any plans to implement this in future?

## Relevant Links

AoT : https://angular.io/docs/ts/latest/cookbook/aot-compiler.html
Angular Universal : https://universal.angular.io

**Comment by Swiip** [comment]
Closing as duplicate for https://github.com/FountainJS/generator-fountain-webapp/issues/167
