### ISSUE TITLE
Update to angular2.rc-3

### ISSUE THREAD

**Issue by wembernard** [FountainJS/generator-fountain-angular2#64]
Angular2 RC3 has been released 👍

**Comment by zckrs** [comment]
https://github.com/FountainJS/generator-fountain-angular2/pull/63

Already done

**Comment by wembernard** [comment]
woops, my bad 👍

**Comment by zckrs** [comment]
Np

I let open we wil close when released so you get notified

**Comment by wembernard** [comment]
Thanks

**Comment by wembernard** [comment]
@zckrs Sorry to bother but would you have any update on this? Are you planning to release `generator-fountain-angular2` anytime soon?

**Comment by micaelmbagira** [comment]
rc4 is part of next release 😉
