### ISSUE TITLE
Sugestion for include html file creation with ang2 generator

### ISSUE THREAD

**Issue by jordaofranca** [FountainJS/generator-fountain-angular2#84]
New components dont have any option to create with require html file and a html file with the component name. The main foutainjs angular 2 generator create hello.ts with:
`@Component({
  selector: 'fountain-app',
  template: require('./hello.html')
})`

it would be nice to include this option in generator.

**Comment by Swiip** [comment]
Component generator will be upgraded with angular 2 final support. This will me aligned.

**Comment by zckrs** [comment]
We have release a new version https://github.com/FountainJS/generator-fountain-webapp/releases/tag/v1.0.0-rc1 who contains Angular2 final stable version.
